--column order: surrogate keys, business keys, major descriptive attribute (high cardinality), Dates attribute (when), minor descriptive attributes (lower cardinality)
select 
base.stg_wop_we_wdj_surrogate_key AS wip_jobs_and_operations_sk,
base.we_wip_entity_id AS we_wip_entity_id,
base.wop_fm_operation_sequence_id AS wop_fm_operation_sequence_id,
base.wdj_common_bom_sequence_id AS wdj_common_bom_sequence_id,
base.wdj_common_routing_sequence_id AS wdj_common_routing_sequence_id,
base.we_wip_entity_name AS "Job Number",
base.wop_fm_operation_seq_num AS "From Op Seq Num",
base.wop_fm_previous_operation_seq_num,
base.wop_fm_next_operation_seq_num,
base.wop_fm_description AS "From Op Desc",
base.wdj_scheduled_start_date AS "Job Scheduled Start Date",
base.wdj_scheduled_completion_date AS "Job Scheduled Completion Date",
base.wop_fm_quantity_in_queue AS "Fm Op Qty in Queue",
base.wop_fm_quantity_waiting_to_move AS "Fm Op To Move Qty",
base.wop_fm_scheduled_quantity AS "Fm Op Scheduled Qty",
base.wop_fm_quantity_completed AS "Fm Op Qty Completed",
base.wop_fm_quantity_running AS "Fm Op Qty Running",
base.wop_fm_quantity_rejected AS "Fm Op Qty Rejected",
base.wop_fm_quantity_scrapped AS "Fm Op Qty Scrapped",
base.wop_fm_quantity_completed AS "Fm Op Qty Completed",
(base.wop_fm_scheduled_quantity - base.wop_fm_quantity_completed - base.wop_fm_quantity_scrapped) AS "Fm Op Qty Remaining",
(base.wdj_start_quantity - base.wdj_quantity_completed - base.wdj_quantity_scrapped) AS "Job Qty Remaining",
base.wop_fm_department_id as wop_fm_department_id,
base.wdj_class_code AS "Job Class Code",
base.meaning_wdj_status_type AS "WIP Job Status",
base.wdj_source_code AS "Job Source Code",
base.wdj_primary_item_id AS "wdj_primary_item_id"
from {{ ref('stg_wop_we_wdj') }} base