SELECT
    reservation_id AS sn_reservation_id,
    n_attribute1 AS sn_n_attribute1,
    n_attribute2 AS sn_n_attribute2,
    n_attribute3 AS sn_n_attribute3,
    n_attribute4 AS sn_n_attribute4,
    n_attribute5 AS sn_n_attribute5,
    n_attribute6 AS sn_n_attribute6,
    n_attribute7 AS sn_n_attribute7,
    n_attribute8 AS sn_n_attribute8,
    n_attribute9 AS sn_n_attribute9,
    n_attribute10 AS sn_n_attribute10,
    status_id AS sn_status_id,
    cost_group_id AS sn_cost_group_id,
    previous_status AS sn_previous_status,
    organization_type AS sn_organization_type,
    owning_organization_id AS sn_owning_organization_id,
    owning_tp_type AS sn_owning_tp_type,
    planning_organization_id AS sn_planning_organization_id,
    planning_tp_type AS sn_planning_tp_type,
    inventory_item_id AS sn_inventory_item_id,
    serial_number AS sn_serial_number,
    last_update_date AS sn_last_update_date,
    last_updated_by AS sn_last_updated_by,
    creation_date AS sn_creation_date,
    created_by AS sn_created_by,
    last_update_login AS sn_last_update_login,
    request_id AS sn_request_id,
    initialization_date AS sn_initialization_date,
    completion_date AS sn_completion_date,
    ship_date AS sn_ship_date,
    current_status AS sn_current_status,
    parent_item_id AS sn_parent_item_id,
    original_wip_entity_id AS sn_original_wip_entity_id,
    original_unit_vendor_id AS sn_original_unit_vendor_id,
    last_txn_source_type_id AS sn_last_txn_source_type_id,
    last_transaction_id AS sn_last_transaction_id,
    last_receipt_issue_type AS sn_last_receipt_issue_type,
    last_txn_source_name AS sn_last_txn_source_name,
    last_txn_source_id AS sn_last_txn_source_id,
    current_subinventory_code AS sn_current_subinventory_code,
    current_locator_id AS sn_current_locator_id,
    current_organization_id AS sn_current_organization_id,
    group_mark_id AS sn_group_mark_id,
    line_mark_id AS sn_line_mark_id,
    lot_line_mark_id AS sn_lot_line_mark_id,
    gen_object_id AS sn_gen_object_id
FROM
    {{ source(
        'inv',
        'mtl_serial_numbers'
    ) }}
WHERE
    planning_organization_id = 1213
