SELECT
    transaction_id AS mt_transaction_id,
    last_update_date AS mt_last_update_date,
    last_updated_by AS mt_last_updated_by,
    creation_date AS mt_creation_date,
    created_by AS mt_created_by,
    last_update_login AS mt_last_update_login,
    request_id AS mt_request_id,
    program_application_id AS mt_program_application_id,
    program_id AS mt_program_id,
    program_update_date AS mt_program_update_date,
    inventory_item_id AS mt_inventory_item_id,
    organization_id AS mt_organization_id,
    subinventory_code AS mt_subinventory_code,
    locator_id AS mt_locator_id,
    transaction_type_id AS mt_transaction_type_id,
    transaction_action_id AS mt_transaction_action_id,
    transaction_source_type_id AS mt_transaction_source_type_id,
    transaction_source_id AS mt_transaction_source_id,
    transaction_source_name AS mt_transaction_source_name,
    transaction_quantity AS mt_transaction_quantity,
    transaction_uom AS mt_transaction_uom,
    primary_quantity AS mt_primary_quantity,
    transaction_date AS mt_transaction_date,
    acct_period_id AS mt_acct_period_id,
    transaction_reference AS mt_transaction_reference,
    cost_update_id AS mt_cost_update_id,
    actual_cost AS mt_actual_cost,
    prior_cost AS mt_prior_cost,
    new_cost AS mt_new_cost,
    currency_conversion_type AS mt_currency_conversion_type,
    quantity_adjusted AS mt_quantity_adjusted,
    department_id AS mt_department_id,
    operation_seq_num AS mt_operation_seq_num,
    trx_source_line_id AS mt_trx_source_line_id,
    transfer_transaction_id AS mt_transfer_transaction_id,
    transaction_set_id AS mt_transaction_set_id,
    move_transaction_id AS mt_move_transaction_id,
    source_code AS mt_source_code,
    source_line_id AS mt_source_line_id,
    transfer_organization_id AS mt_transfer_organization_id,
    transfer_subinventory AS mt_transfer_subinventory,
    cost_group_id AS mt_cost_group_id,
    transfer_cost_group_id AS mt_transfer_cost_group_id,
    mvt_stat_status AS mt_mvt_stat_status,
    move_order_line_id AS mt_move_order_line_id,
    pick_rule_id AS mt_pick_rule_id,
    organization_type AS mt_organization_type,
    transfer_organization_type AS mt_transfer_organization_type,
    owning_organization_id AS mt_owning_organization_id,
    owning_tp_type AS mt_owning_tp_type,
    xfr_owning_organization_id AS mt_xfr_owning_organization_id,
    transfer_owning_tp_type AS mt_transfer_owning_tp_type,
    planning_organization_id AS mt_planning_organization_id,
    planning_tp_type AS mt_planning_tp_type,
    xfr_planning_organization_id AS mt_xfr_planning_organization_id,
    transfer_planning_tp_type AS mt_transfer_planning_tp_type,
    transaction_mode AS mt_transaction_mode,
    transaction_batch_id AS mt_transaction_batch_id,
    transaction_batch_seq AS mt_transaction_batch_seq,
    reason_id AS mt_reason_id,
    transfer_price AS mt_transfer_price,
    lu_mtl_tt_transaction_type_name,
    lu_mtl_tt_description
FROM
    {{ source('inv','mtl_material_transactions') }}
LEFT JOIN {{ ref('lu_mtl_transaction_types') }} lu
ON transaction_type_id = lu.lu_mtl_tt_transaction_type_id
WHERE
    organization_id = 1213