SELECT
    enable_locator_alias AS msub_enable_locator_alias,
    enforce_alias_uniqueness AS msub_enforce_alias_uniqueness,
    enable_opp_cyc_count AS msub_enable_opp_cyc_count,
    depreciable_flag AS msub_depreciable_flag,
    default_cost_group_id AS msub_default_cost_group_id,
    status_id AS msub_status_id,
    default_loc_status_id AS msub_default_loc_status_id,
    lpn_controlled_flag AS msub_lpn_controlled_flag,
    cartonization_flag AS msub_cartonization_flag,
    subinventory_type AS msub_subinventory_type,
    planning_level AS msub_planning_level,
    default_count_type_code AS msub_default_count_type_code,
    enable_bulk_pick AS msub_enable_bulk_pick,
    secondary_inventory_name AS msub_secondary_inventory_name,
    organization_id AS msub_organization_id,
    last_update_date AS msub_last_update_date,
    last_updated_by AS msub_last_updated_by,
    creation_date AS msub_creation_date,
    created_by AS msub_created_by,
    last_update_login AS msub_last_update_login,
    description AS msub_description,
    inventory_atp_code AS msub_inventory_atp_code,
    availability_type AS msub_availability_type,
    reservable_type AS msub_reservable_type,
    locator_type AS msub_locator_type,
    picking_order AS msub_picking_order,
    material_account AS msub_material_account,
    material_overhead_account AS msub_material_overhead_account,
    resource_account AS msub_resource_account,
    overhead_account AS msub_overhead_account,
    outside_processing_account AS msub_outside_processing_account,
    quantity_tracked AS msub_quantity_tracked,
    asset_inventory AS msub_asset_inventory,
    requisition_approval_type AS msub_requisition_approval_type,
    expense_account AS msub_expense_account
FROM
    {{ source('inv', 'mtl_secondary_inventories') }}
WHERE
    organization_id = 1213
