-- THIS IS THE SCRIPT FOR THE TABLEAU DASHBOARD CALLED PROD_MoveTransactions
-- from legacy code (initial creation 7/10/25)
SELECT
    WMT.TRANSACTION_ID
  , WMT.TRANSACTION_DATE        AS "TRANSACTION DATE"
  , MS.SEGMENT1                 AS "PART NUMBER"
  , MS.DESCRIPTION              AS "PART DESCRIPTION"
  , WE.WIP_ENTITY_NAME          AS "WIP ENTITY NAME"
  , WMT.FM_OPERATION_SEQ_NUM    AS "FM OP SEQ NUM"
  , FMBOS.OPERATION_DESCRIPTION AS "FM OP DESC"
  , WMT.FM_OPERATION_CODE
  , FMD.DEPARTMENT_CODE         AS "FM DEPARTMENT"
  , FM_INTRAOPERATION_STEP_TYPE
  , WMT.TO_OPERATION_SEQ_NUM    AS "TO OP SEQ NUM"
  , TOBOS.OPERATION_DESCRIPTION AS "TO OP DESC"
  , WMT.TO_OPERATION_CODE
  , TOD.DEPARTMENT_CODE         AS "TO DEPARTMENT"
  , WMT.TO_INTRAOPERATION_STEP_TYPE
  , WMT.TRANSACTION_QUANTITY    AS "TRANSACTION QUANTITY"
  , WMT.TRANSACTION_UOM
  , WMT.PRIMARY_QUANTITY
  , WMT.PRIMARY_UOM
  , MS.SEGMENT1    || '_' || WMT.FM_OPERATION_SEQ_NUM    AS "Material_OP"
FROM
    WIP.WIP_MOVE_TRANSACTIONS WMT
    JOIN WIP.WIP_OPERATIONS FMWOP
        ON WMT.WIP_ENTITY_ID = FMWOP.WIP_ENTITY_ID 
            AND WMT.FM_OPERATION_SEQ_NUM = FMWOP.OPERATION_SEQ_NUM
            AND WMT.ORGANIZATION_ID = FMWOP.ORGANIZATION_ID
    JOIN WIP.WIP_OPERATIONS TOWOP
        ON WMT.WIP_ENTITY_ID = TOWOP.WIP_ENTITY_ID 
            AND WMT.FM_OPERATION_SEQ_NUM = TOWOP.OPERATION_SEQ_NUM
            AND WMT.ORGANIZATION_ID = TOWOP.ORGANIZATION_ID
    JOIN BOM.BOM_OPERATION_SEQUENCES FMBOS
        ON FMWOP.OPERATION_SEQUENCE_ID = FMBOS.OPERATION_SEQUENCE_ID
    JOIN BOM.BOM_OPERATION_SEQUENCES TOBOS
        ON FMWOP.OPERATION_SEQUENCE_ID = TOBOS.OPERATION_SEQUENCE_ID  
    JOIN APPS.BOM_DEPARTMENTS FMD
        ON WMT.FM_DEPARTMENT_ID = FMD.DEPARTMENT_ID
    JOIN APPS.BOM_DEPARTMENTS TOD
        ON WMT.TO_DEPARTMENT_ID = TOD.DEPARTMENT_ID
    JOIN WIP.WIP_ENTITIES WE 
        ON WMT.WIP_ENTITY_ID = WE.WIP_ENTITY_ID
    JOIN INV.MTL_SYSTEM_ITEMS_B MS
        ON WMT.PRIMARY_ITEM_ID = MS.INVENTORY_ITEM_ID
        AND WMT.ORGANIZATION_ID = MS.ORGANIZATION_ID 
WHERE
    WMT.ORGANIZATION_ID = 1213
    AND WMT.TRANSACTION_DATE >= SYSDATE - 120
    AND WMT.SCRAP_ACCOUNT_ID IS NULL
;
/*
RC01 Completion per unit ATO Serialized Number
RC02 Serialzied for Inspection for over 60 units?
At final inspection step, sent "To Move" queue for completion or "To Scrap" Intraoperation Step if Scrap

NASM- non applicable scrap move

What is TID for rest of USC?


Release 4 coming next few weeks
Updates: new package to put in occurrance id and serial number in WIP MOVES TRANSACTIONS
Line ID = Occurence id
RESULTS RECORDING FOR SN MOVE TRXNS
Using Transact Date, or Inspection Date, or Creation Date


Source Code
OA Transactions move from MES
Blanks are from Java


MRP SLT- simulation; different MDS for simulations; adjust item lead times, adjust demands, 
MIDAS report compares Simulation to MDS

*/