WITH RTY_CTE AS(
SELECT * FROM
(
SELECT
    TRUNC (WMT.TRANSACTION_DATE, 'MM') AS "FIRST MONTH DATE"
  , WMT.FM_OPERATION_SEQ_NUM           AS "FM OP SEQ NUM RTY" -- 4
  , MS.SEGMENT1                        AS "PART NUMBER RTY" -- 5
  , SUM (WMT.TRANSACTION_QUANTITY)     AS "TRANSACTION QTY RTY" -- 8
  , 'RTY_CONFIRMATIONS'                AS FEATURE
FROM
    WIP.WIP_MOVE_TRANSACTIONS     WMT
    JOIN WIP.WIP_OPERATIONS FMWOP
    ON WMT.WIP_ENTITY_ID = FMWOP.WIP_ENTITY_ID
    AND WMT.FM_OPERATION_SEQ_NUM = FMWOP.OPERATION_SEQ_NUM
    AND WMT.ORGANIZATION_ID = FMWOP.ORGANIZATION_ID
    JOIN WIP.WIP_OPERATIONS TOWOP
    ON WMT.WIP_ENTITY_ID = TOWOP.WIP_ENTITY_ID
    AND WMT.FM_OPERATION_SEQ_NUM = TOWOP.OPERATION_SEQ_NUM
    AND WMT.ORGANIZATION_ID = TOWOP.ORGANIZATION_ID
    JOIN BOM.BOM_OPERATION_SEQUENCES FMBOS
    ON FMWOP.OPERATION_SEQUENCE_ID = FMBOS.OPERATION_SEQUENCE_ID
    JOIN BOM.BOM_OPERATION_SEQUENCES TOBOS
    ON FMWOP.OPERATION_SEQUENCE_ID = TOBOS.OPERATION_SEQUENCE_ID
    JOIN APPS.BOM_DEPARTMENTS FMD
    ON WMT.FM_DEPARTMENT_ID = FMD.DEPARTMENT_ID
    JOIN APPS.BOM_DEPARTMENTS TOD
    ON WMT.TO_DEPARTMENT_ID = TOD.DEPARTMENT_ID
    JOIN WIP.WIP_ENTITIES WE
    ON WMT.WIP_ENTITY_ID = WE.WIP_ENTITY_ID
    JOIN INV.MTL_SYSTEM_ITEMS_B MS
    ON WMT.PRIMARY_ITEM_ID = MS.INVENTORY_ITEM_ID
    AND WMT.ORGANIZATION_ID = MS.ORGANIZATION_ID
    LEFT JOIN APPS.FND_USER
    ON FND_USER.USER_ID = WMT.CREATED_BY
WHERE
    WMT.ORGANIZATION_ID = 1213
    AND WMT.TRANSACTION_DATE >= '01-MAY-2025'
    AND WMT.SCRAP_ACCOUNT_ID IS NULL -- Remove Scrap Qtys
    AND (MS.SEGMENT1 IN ('966-4516-007', '966-4518-006', '987-0018-661', '987-0018-661+PR')
      OR MS.SEGMENT1 LIKE '966-2083%')
GROUP BY
    TRUNC (WMT.TRANSACTION_DATE, 'MM')
  , WMT.FM_OPERATION_SEQ_NUM
  , MS.SEGMENT1
UNION
ALL
SELECT
    TRUNC (QR.QA_CREATION_DATE, 'MM')  AS "FIRST MONTH DATE"
  , QR.FROM_OP_SEQ_NUM                 AS "FM OP SEQ NUM" -- 4
  , MSIK.SEGMENT1                      AS "PART NUMBER" -- 5
  , SUM (QR.QUANTITY)                  AS "TRANSACTION QTY" -- 8
  , 'RTY_DEFECTS'
FROM
    APPS.QA_RESULTS               QR
  , APPS.QA_PLANS                 QP
  , APPS.MTL_SYSTEM_ITEMS_B       MSIK
  , APPS.QA_RESULTS               QRESULT
  , APPS.QA_PLANS                 QRESULTP
  , QA.QA_PC_RESULTS_RELATIONSHIP PCH
WHERE
    QP.NAME = 'DEFECT DETAILS NSS'
    AND QR.PLAN_ID = QP.PLAN_ID
    AND QP.PLAN_ID = QR.PLAN_ID
    AND QR.ITEM_ID = MSIK.INVENTORY_ITEM_ID (+)
    AND QR.ORGANIZATION_ID = MSIK.ORGANIZATION_ID (+)
    AND (QR.STATUS IS NULL
    OR QR.STATUS = 2)
    AND (PCH.CHILD_PLAN_ID = QR.PLAN_ID (+)
    AND PCH.CHILD_OCCURRENCE = QR.OCCURRENCE (+)
    AND PCH.CHILD_COLLECTION_ID = QR.COLLECTION_ID (+) )
    AND QR.ORGANIZATION_ID IN (1213, 1273)
    AND QR.QA_CREATION_DATE >= '01-MAY-2025'
 -- Added 3/14/23 --
    AND QRESULTP.NAME = 'RESULTS RECORDING NSS'
    AND QRESULTP.PLAN_ID = QRESULT.PLAN_ID
    AND PCH.PARENT_PLAN_ID = QRESULT.PLAN_ID
    AND PCH.PARENT_COLLECTION_ID =QRESULT.COLLECTION_ID
    AND PCH.PARENT_OCCURRENCE = QRESULT.OCCURRENCE
    AND (MSIK.SEGMENT1 IN ('966-4516-007', '966-4518-006', '987-0018-661', '987-0018-661+PR')
      OR MSIK.SEGMENT1 LIKE '966-2083%')
GROUP BY
    TRUNC (QR.QA_CREATION_DATE, 'MM')
  , QR.FROM_OP_SEQ_NUM
  , MSIK.SEGMENT1
)
PIVOT (
    SUM("TRANSACTION QTY RTY") AS SUM_QTY
    FOR FEATURE IN ('RTY_CONFIRMATIONS' AS "RTY_CONFIRMATIONS",'RTY_DEFECTS' AS "RTY_DEFECTS")
)

)

SELECT 
  RTY."PART NUMBER RTY"
  , RTY."FIRST MONTH DATE"
  , RTY."FM OP SEQ NUM RTY"
  , RTY.TOT_CONFIRMS
  , RTY.TOT_DEFECTS
  , RTY.YIELD_RATIO
  , ROUND(EXP(SUM
        (
        CASE
            WHEN RTY.YIELD_RATIO = 0 THEN NULL
            ELSE LN(RTY.YIELD_RATIO)
        END 
        ) 
        OVER (PARTITION BY "PART NUMBER RTY", "FIRST MONTH DATE" ORDER BY RTY."FM OP SEQ NUM RTY")),4)
        AS CUMU_YIELD_PERCENT
  , ROUND(EXP(SUM
        (
        CASE
            WHEN RTY.YIELD_RATIO = 0 THEN NULL
            ELSE LN(RTY.YIELD_RATIO)
        END 
        ) 
        OVER (PARTITION BY "FIRST MONTH DATE" ORDER BY RTY."FM OP SEQ NUM RTY")),4)
        AS ALL_CUMU_YIELD_PERCENT
  , ROUND(SUM(
        CASE
            WHEN RTY.YIELD_RATIO = 0 THEN NULL
            ELSE LN(RTY.YIELD_RATIO)
        END 
        )  
        OVER (PARTITION BY "PART NUMBER RTY", "FIRST MONTH DATE" ORDER BY RTY."FM OP SEQ NUM RTY"),4) 
        AS SUM_LN_YIELD
FROM
(
SELECT
    RTY_CTE."PART NUMBER RTY"
  , RTY_CTE."FIRST MONTH DATE"
  , RTY_CTE."FM OP SEQ NUM RTY"
  , NVL (RTY_CTE.RTY_CONFIRMATIONS_SUM_QTY, 0)                                                AS TOT_CONFIRMS
  , NVL (RTY_CTE.RTY_DEFECTS_SUM_QTY, 0)                                                      AS TOT_DEFECTS
  , ROUND (NVL (RTY_CTE.RTY_CONFIRMATIONS_SUM_QTY, 0) 
  / (NVL (RTY_CTE.RTY_CONFIRMATIONS_SUM_QTY, 0) + NVL (RTY_CTE.RTY_DEFECTS_SUM_QTY, 0) ) , 4) AS YIELD_RATIO
FROM
    RTY_CTE
) RTY