SELECT
    primary_phone_area_code AS hz_p_primary_phone_area_code,
    primary_phone_number AS hz_p_primary_phone_number,
    orig_system_reference AS hz_p_orig_system_reference,
    customer_key AS hz_p_customer_key,
    person_first_name AS hz_p_person_first_name,
    person_last_name AS hz_p_person_last_name,
    country AS hz_p_country,
    address1 AS hz_p_address1,
    city AS hz_p_city,
    postal_code AS hz_p_postal_code,
    status AS hz_p_status,
    email_address AS hz_p_email_address,
    object_version_number AS hz_p_object_version_number,
    created_by_module AS hz_p_created_by_module,
    application_id AS hz_p_application_id,
    primary_phone_contact_pt_id AS hz_p_primary_phone_contact_pt_id,
    primary_phone_line_type AS hz_p_primary_phone_line_type,
    party_id AS hz_p_party_id,
    party_number AS hz_p_party_number,
    party_name AS hz_p_party_name,
    party_type AS hz_p_party_type,
    validated_flag AS hz_p_validated_flag,
    last_updated_by AS hz_p_last_updated_by,
    creation_date AS hz_p_creation_date,
    last_update_login AS hz_p_last_update_login,
    created_by AS hz_p_created_by,
    last_update_date AS hz_p_last_update_date,
    program_update_date AS hz_p_program_update_date
FROM
    apps.hz_parties
