SELECT
    operation_sequence_id AS bos_operation_sequence_id,
    routing_sequence_id AS bos_routing_sequence_id,
    operation_seq_num AS bos_operation_seq_num,
    last_update_date AS bos_last_update_date,
    last_updated_by AS bos_last_updated_by,
    creation_date AS bos_creation_date,
    created_by AS bos_created_by,
    last_update_login AS bos_last_update_login,
    department_id AS bos_department_id,
    operation_lead_time_percent AS bos_operation_lead_time_percent,
    minimum_transfer_quantity AS bos_minimum_transfer_quantity,
    count_point_type AS bos_count_point_type,
    operation_description AS bos_operation_description,
    effectivity_date AS bos_effectivity_date,
    backflush_flag AS bos_backflush_flag,
    option_dependent_flag AS bos_option_dependent_flag,
    attribute13 AS bos_attribute13,
    attribute14 AS bos_attribute14,
    request_id AS bos_request_id,
    program_application_id AS bos_program_application_id,
    program_id AS bos_program_id,
    program_update_date AS bos_program_update_date,
    operation_type AS bos_operation_type,
    reference_flag AS bos_reference_flag,
    labor_time_user AS bos_labor_time_user,
    machine_time_user AS bos_machine_time_user,
    total_time_user AS bos_total_time_user,
    include_in_rollup AS bos_include_in_rollup,
    operation_yield_enabled AS bos_operation_yield_enabled,
    implementation_date AS bos_implementation_date,
    eco_for_production AS bos_eco_for_production
FROM
    apps.bom_operation_sequences