/*
****
****
BAE_CONTEXT001_EXPLODED_BOMS
NOTE: BOM_EXPLOSIONS and BOM_EXPLOSIONS_ALL does not exist in our oracle ebs instance.
*/
SELECT
BOMS.BOM_LEVEL
, BOMS.TOP_ITEM_NUMBER
, BOMS.TOP_ITEM_DESCRIPTION
, BOMS.ASSEMBLY_ITEM_NUMBER
, BOMS.ASSEMBLY_ITEM_DESCRIPTION
, BOMS.COMPONENT_ITEM_NUMBER
, BOMS.COMPONENT_ITEM_DESCRIPTION
, BOMS.MAKE_BUY_CODE
, BOMS.REF_DESIGNATORS
, BOMS.TOP_ITEM_ID
, BOMS.SORT_ORDER_NUMBER
, BOMS.ASSEMBLY_ITEM_ID
, BOMS.COMPONENT_ITEM_ID
, BOMS.COMPONENT_SEQUENCE
, BOMS.COMPONENT_QUANTITY
, BOMS.COMPONENT_BOM_TOTAL_QTY
, BOMS.EFFECTIVITY_DATE
, BOMS.IMPLEMENTATION_DATE
FROM BAE.BAE_CONTEXT001_EXPLODED_BOMS BOMS
WHERE BOMS.ORGANIZATION_ID = 1213
AND BOMS.TOP_ITEM_NUMBER LIKE '987-2094-004'
--AND BOMS.TOP_ITEM_NUMBER LIKE '944-3765-008'
--AND BOMS.COMPONENT_ITEM_NUMBER LIKE '384-0052-140'
--AND BOMS.MAKE_BUY_CODE = 'MAKE'
AND BOMS.REF_DESIGNATORS IS NOT NULL 
-- when reference signators IS NULL: components without a physical location on the board or within assembly. Components like Spec Documents, Firmware/Software, or Mechanical items physical not on board
ORDER BY BOMS.BOM_LEVEL, boms.top_item_number, boms.assembly_item_number, boms.sort_order_number;
SELECT DISTINCT 
BOMS.TOP_ITEM_NUMBER
, BOMS.TOP_ITEM_DESCRIPTION
, BOMS.MAKE_BUY_CODE
, BOMS.BOM_LEVEL
, BOMS.REF_DESIGNATORS
FROM BAE.BAE_CONTEXT001_EXPLODED_BOMS BOMS
WHERE BOMS.ORGANIZATION_ID = 1213
AND BOMS.MAKE_BUY_CODE = 'MAKE'
AND BOMS.BOM_LEVEL = 1
AND BOMS.REF_DESIGNATORS IS NOT NULL
;
SELECT DISTINCT 
BOMS.TOP_ITEM_NUMBER
, BOMS.TOP_ITEM_DESCRIPTION
, BOMS.ASSEMBLY_ITEM_NUMBER
, BOMS.ASSEMBLY_ITEM_DESCRIPTION
, BOMS.MAKE_BUY_CODE
, BOMS.BOM_LEVEL
, BOMS.REF_DESIGNATORS
FROM BAE.BAE_CONTEXT001_EXPLODED_BOMS BOMS
WHERE BOMS.ORGANIZATION_ID = 1213
AND BOMS.MAKE_BUY_CODE = 'MAKE'
AND BOMS.BOM_LEVEL = 1
AND BOMS.REF_DESIGNATORS IS NOT NULL
--AND boms.ASSEMBLY_ITEM_NUMBER like '987-2094-004'
;