SELECT * FROM WIP_LOGGER;


-- https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/ALL_OBJECTS.html#GUID-AA6DEF8B-F04F-482A-8440-DBCB18F6C976
-- ALL_OBJECTS: RETURNS ALL OBJECTS i HAVE ACCESS TO
SELECT * 
FROM ALL_OBJECTS 
WHERE OBJECT_NAME LIKE '%WIP%' 
;
SELECT * 
FROM ALL_OBJECTS 
WHERE OBJECT_NAME LIKE '%BOM%' 
;
SELECT * 
FROM ALL_OBJECTS 
WHERE OBJECT_NAME LIKE '%SYS%' 
;
SELECT * 
FROM ALL_OBJECTS 
WHERE OBJECT_NAME LIKE '%LOG%' 
ORDER BY OBJECT_NAME
;

SELECT * FROM ALL_LOG_GROUPS; -- O ROWS

SELECT * FROM DBMS_LOG;
SELECT * FROM ALL_LOG_GROUP_COLUMNS; -- 0 ROWS
SELECT * FROM ALL_SNAPSHOT_LOGS; -- 0 ROWS
SELECT * FROM DBMS_LOG;
SELECT * FROM DBA_LOG_GROUP_COLUMNS;
SELECT * FROM DBMS_LOG;

SELECT * FROM GV$LOG;

SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME LIKE '%LOG%';

SELECT * FROM BAE_CONTWFL002_WIP_COMP_LOG;
SELECT DISTINCT ORGANIZATION_ID FROM BAE_CONTWFL002_WIP_COMP_LOG; -- DOES NOT INCLUDE 1213


SELECT * FROM APPS.DBA_HIST_LOG;

SELECT DISTINCT OBJECT_TYPE FROM ALL_OBJECTS WHERE OWNER = 'PUBLIC'; -- INDEX, VIEW, TABLE

SELECT DISTINCT OBJECT_TYPE FROM DBA_OBJECTS WHERE OWNER = 'WIP'; -- NULL


SELECT 
OWNER
, TABLE_NAME
, TABLESPACE_NAME
, STATUS
, NUM_ROWS
FROM ALL_TABLES 
WHERE 1=1 
AND TABLE_NAME LIKE 'ALL_LOG%'
ORDER BY TABLE_NAME;

SELECT 
OWNER
, TABLE_NAME
, TABLESPACE_NAME
, STATUS
, NUM_ROWS
FROM ALL_TABLES 
WHERE 1=1 
AND OWNER LIKE '%SYS%'
ORDER BY NUM_ROWS;

SELECT 
OWNER
, TABLE_NAME
, TABLESPACE_NAME
, STATUS
, NUM_ROWS
FROM ALL_TABLES 
WHERE 1=1 
AND TABLE_NAME LIKE '%FND%'
ORDER BY TABLE_NAME;

SELECT * FROM APPLSYS.FND_ATTACHED_DOCUMENTS 
WHERE CREATION_DATE > '01=JAN-2024'
AND PK3_VALUE = 1213;

SELECT DISTINCT ENTITY_NAME FROM APPLSYS.FND_ATTACHED_DOCUMENTS 
WHERE CREATION_DATE > '01=JAN-2024'
AND PK3_VALUE = 1213;

SELECT * FROM APPLSYS.FND_CONCURRENT_REQUESTS; -- NO ACCESS

SELECT * FROM FND_PRIMARY_KEYS WHERE PRIMARY_KEY_NAME LIKE 'WIP%';
SELECT * FROM FND_FOREIGN_KEYS WHERE FOREIGN_KEY_NAME LIKE 'WIP%';

SELECT * FROM APPLSYSPUB.FND_MESSAGE; -- NULL

SELECT * FROM APPLSYSPUB.FND_PUB_MESSAGE;


SELECT 
OWNER
, TABLE_NAME
, TABLESPACE_NAME
, STATUS
, NUM_ROWS
FROM ALL_TABLES 
WHERE 1=1 
AND TABLE_NAME LIKE 'WIP%'

;

SELECT 
OWNER
, TABLE_NAME
, TABLESPACE_NAME
, STATUS
, NUM_ROWS
, LAST_ANALYZED
FROM ALL_TABLES 
WHERE 1=1 
AND OWNER LIKE 'BAE'
;

SELECT 
OWNER
, TABLE_NAME
, TABLESPACE_NAME
, STATUS
, NUM_ROWS
, LAST_ANALYZED
FROM ALL_TABLES 
WHERE 1=1 
AND OWNER LIKE 'MRP'
--AND TABLE_NAME LIKE '%MRP%'
;

SELECT * FROM ALL_TABLES;


SELECT * FROM USER_OBJECTS --WHERE OBJECT_TYPE LIKE 'FUNCTION'
;

SELECT DISTINCT OBJECT_TYPE FROM USER_OBJECTS;

SELECT DISTINCT 
*
FROM BAE.BAE_CONTEXT248_MRP_ARCHIVE
WHERE MRP_RUN_DATE >= '01-JAN-24';

SELECT DISTINCT 
* 
FROM BAE.BAE_CONTHDB031_MRP_OTHER_ORG;