select
    tl_outside_processing_var as wpb_tl_outside_processing_var,
    tl_overhead_var as wpb_tl_overhead_var,
    pl_material_var as wpb_pl_material_var,
    pl_material_overhead_var as wpb_pl_material_overhead_var,
    pl_resource_var as wpb_pl_resource_var,
    pl_overhead_var as wpb_pl_overhead_var,
    pl_outside_processing_var as wpb_pl_outside_processing_var,
    tl_scrap_out as wpb_tl_scrap_out,
    acct_period_id as wpb_acct_period_id,
    wip_entity_id as wpb_wip_entity_id,
    last_update_date as wpb_last_update_date,
    last_updated_by as wpb_last_updated_by,
    creation_date as wpb_creation_date,
    created_by as wpb_created_by,
    last_update_login as wpb_last_update_login,
    organization_id as wpb_organization_id,
    class_type as wpb_class_type,
    tl_resource_in as wpb_tl_resource_in,
    tl_overhead_in as wpb_tl_overhead_in,
    tl_outside_processing_in as wpb_tl_outside_processing_in,
    pl_material_in as wpb_pl_material_in,
    pl_material_overhead_in as wpb_pl_material_overhead_in,
    pl_resource_in as wpb_pl_resource_in,
    pl_overhead_in as wpb_pl_overhead_in,
    pl_outside_processing_in as wpb_pl_outside_processing_in,
    tl_material_out as wpb_tl_material_out,
    tl_material_overhead_out as wpb_tl_material_overhead_out,
    tl_resource_out as wpb_tl_resource_out,
    tl_overhead_out as wpb_tl_overhead_out,
    tl_outside_processing_out as wpb_tl_outside_processing_out,
    pl_material_out as wpb_pl_material_out,
    pl_material_overhead_out as wpb_pl_material_overhead_out,
    pl_resource_out as wpb_pl_resource_out,
    pl_overhead_out as wpb_pl_overhead_out,
    pl_outside_processing_out as wpb_pl_outside_processing_out,
    request_id as wpb_request_id,
    program_application_id as wpb_program_application_id,
    program_id as wpb_program_id,
    program_update_date as wpb_program_update_date,
    tl_material_var as wpb_tl_material_var,
    tl_material_overhead_var as wpb_tl_material_overhead_var,
    tl_resource_var as wpb_tl_resource_var
FROM
    {{ source('wip', 'wip_period_balances') }}
WHERE
    organization_id = 1213
