select msib.inventory_item_status_code, mis.description, count(*) 
from apps.mtl_system_items_b msib join apps.mtl_item_status_tl mis
on msib.inventory_item_status_code = mis.inventory_item_status_code
where organization_id = 1213
group by msib.inventory_item_status_code, mis.description
order by 2 desc;

/*  MTL SYSTEM ITEMS B LOOKUPS
*
*
*
*/
SELECT DISTINCT
  LU1.MEANING 
  , LU1.LOOKUP_TYPE 
  , LU1.LOOKUP_CODE  
FROM APPS.FND_LOOKUP_VALUES LU1
WHERE LU1.LOOKUP_TYPE LIKE 'MTL_PLANNING_MAKE_BUY'
ORDER BY TO_NUMBER(LU1.LOOKUP_CODE);


/* MTL MATERIAL TRANSACTIONS LOOKUPs
*
*
*
*/
SELECT DISTINCT
MT.TRANSACTION_SOURCE_TYPE_ID
, LU1.TRANSACTION_SOURCE_TYPE_ID
, LU1.DESCRIPTION
, MT.TRANSACTION_ACTION_ID
, LU2.LOOKUP_CODE
, LU2.MEANING
, MT.REASON_ID
, LU3.REASON_ID
, LU3.DESCRIPTION
, LU4.TRANSACTION_TYPE_ID
, LU4.TRANSACTION_TYPE_ID
, LU4.DESCRIPTION

FROM INV.MTL_MATERIAL_TRANSACTIONS MT
LEFT JOIN INV.MTL_TXN_SOURCE_TYPES LU1
    ON MT.TRANSACTION_SOURCE_TYPE_ID = LU1.TRANSACTION_SOURCE_TYPE_ID
LEFT JOIN APPS.FND_LOOKUP_VALUES LU2
    ON MT.TRANSACTION_ACTION_ID = LU2.LOOKUP_CODE
    AND LU2.LOOKUP_TYPE = 'MTL_TRANSACTION_ACTION'
LEFT JOIN INV.MTL_TRANSACTION_REASONS LU3
    ON MT.REASON_ID = LU3.REASON_ID
LEFT JOIN INV.MTL_TRANSACTION_TYPES LU4
    ON MT.TRANSACTION_TYPE_ID = LU4.TRANSACTION_TYPE_ID
WHERE MT.ORGANIZATION_ID = 1213
AND MT.TRANSACTION_DATE >= '01-JUN-24'
;
SELECT DISTINCT
MT.TRANSACTION_SOURCE_TYPE_ID
, LU1.TRANSACTION_SOURCE_TYPE_ID
, LU1.DESCRIPTION
FROM INV.MTL_MATERIAL_TRANSACTIONS MT
LEFT JOIN INV.MTL_TXN_SOURCE_TYPES LU1
    ON MT.TRANSACTION_SOURCE_TYPE_ID = LU1.TRANSACTION_SOURCE_TYPE_ID
WHERE MT.ORGANIZATION_ID = 1213
AND MT.TRANSACTION_DATE >= '01-JUN-24'
ORDER BY MT.TRANSACTION_SOURCE_TYPE_ID
;
SELECT DISTINCT
MT.TRANSACTION_ACTION_ID
, LU2.LOOKUP_CODE
, LU2.MEANING
FROM INV.MTL_MATERIAL_TRANSACTIONS MT
LEFT JOIN APPS.FND_LOOKUP_VALUES LU2
    ON MT.TRANSACTION_ACTION_ID = LU2.LOOKUP_CODE
    AND LU2.LOOKUP_TYPE = 'MTL_TRANSACTION_ACTION'
WHERE MT.ORGANIZATION_ID = 1213
AND MT.TRANSACTION_DATE >= '01-JUN-24'
ORDER BY MT.TRANSACTION_ACTION_ID
;
SELECT DISTINCT
MT.REASON_ID
, LU3.REASON_ID
, LU3.DESCRIPTION
FROM INV.MTL_MATERIAL_TRANSACTIONS MT
LEFT JOIN INV.MTL_TRANSACTION_REASONS LU3
    ON MT.REASON_ID = LU3.REASON_ID
WHERE MT.ORGANIZATION_ID = 1213
AND MT.TRANSACTION_DATE >= '01-JUN-24'
ORDER BY MT.REASON_ID
;
SELECT DISTINCT
LU4.TRANSACTION_TYPE_ID
, LU4.TRANSACTION_TYPE_ID
, LU4.DESCRIPTION
FROM INV.MTL_MATERIAL_TRANSACTIONS MT
LEFT JOIN INV.MTL_TRANSACTION_TYPES LU4
    ON MT.TRANSACTION_TYPE_ID = LU4.TRANSACTION_TYPE_ID
WHERE MT.ORGANIZATION_ID = 1213
AND MT.TRANSACTION_DATE >= '01-JUN-24'
ORDER BY LU4.TRANSACTION_TYPE_ID
;
SELECT DISTINCT
  LU1.MEANING AS MRP_DEMAND_ORIGINATION
  , LU1.LOOKUP_TYPE 
  , LU1.LOOKUP_CODE  
  , LU2.MEANING AS MTL_DEMAND_TYPE
  , LU2.LOOKUP_TYPE 
  , LU2.LOOKUP_CODE  
FROM 
    INV.MTL_DEMAND MD
    LEFT JOIN APPS.FND_LOOKUP_VALUES LU1
    ON MD.DEMAND_SOURCE_TYPE = LU1.LOOKUP_CODE
    AND LU1.LOOKUP_TYPE ='MTL_DEMAND_TYPE'
    LEFT JOIN APPS.FND_LOOKUP_VALUES LU2 
    ON MD.RESERVATION_TYPE = LU2.LOOKUP_CODE
    AND LU2.LOOKUP_TYPE = 'MTL_RESERVATION'
    ORDER BY LU1.LOOKUP_CODE;
  
/* 
****
****
****    LU1.LOOKUP_TYPE ='MTL_DEMAND_TYPE'
****
****
****
*/

SELECT DISTINCT
  LU1.MEANING AS MRP_DEMAND_ORIGINATION
  , LU1.LOOKUP_TYPE 
  , LU1.LOOKUP_CODE  
FROM 
  APPS.FND_LOOKUP_VALUES LU1
WHERE
  LU1.LOOKUP_TYPE ='MTL_DEMAND_TYPE'

ORDER BY LU1.LOOKUP_CODE;

/* 
****
****
****    LU2.LOOKUP_TYPE ='MTL_RESERVATION'
****
****
****
*/
SELECT DISTINCT
  LU2.MEANING AS MRP_DEMAND_ORIGINATION
  , LU2.LOOKUP_TYPE 
  , LU2.LOOKUP_CODE  
FROM
  APPS.FND_LOOKUP_VALUES LU2 
WHERE
  LU2.LOOKUP_TYPE = 'MTL_RESERVATION'

ORDER BY LU2.LOOKUP_CODE;
/* 
****
****
****    LU3.LOOKUP_TYPE ='MTL_TXN_ISSUE_RECEIPT'
****
****
****
*/
SELECT DISTINCT
  LU3.MEANING AS RECEIPT_ISSUE_TYPE
  , LU3.LOOKUP_TYPE 
  , LU3.LOOKUP_CODE  
FROM
  APPS.FND_LOOKUP_VALUES LU3 
WHERE
  LU3.LOOKUP_TYPE = 'MTL_TXN_ISSUE_RECEIPT'

ORDER BY LU3.LOOKUP_CODE;
--
-- EXAMPLE
--
SELECT DISTINCT
  MUT.RECEIPT_ISSUE_TYPE
  , LU2.MEANING AS "RECEIPT ISSUE TYPE"
FROM
    INV.MTL_UNIT_TRANSACTIONS MUT
JOIN APPS.FND_LOOKUP_VALUES LU2
        ON MUT.RECEIPT_ISSUE_TYPE = LU2.LOOKUP_CODE
        AND LU2.LOOKUP_TYPE ='MTL_TXN_ISSUE_RECEIPT'
;
/* 
****
****
****    LU2.LOOKUP_TYPE ='MTL_TRANSACTION_ACTION'
****
****
****
*/
SELECT DISTINCT
  LU2.MEANING AS TRANSACTION_ACTION_TYPE
  , LU2.LOOKUP_TYPE 
  , LU2.LOOKUP_CODE  
FROM
  APPS.FND_LOOKUP_VALUES LU2 
WHERE
  LU2.LOOKUP_TYPE = 'MTL_TRANSACTION_ACTION'

ORDER BY LU2.LOOKUP_CODE;
/* 
****
****
****    INV.MTL_TRANSACTION_TYPES
****
****
****
*/
-- KEYS
-- T.TRANSACTION_TYPE_ID = TLU.TRANSACTION_TYPE_ID
SELECT DISTINCT
    TLU1.TRANSACTION_TYPE_ID
  , TLU1.TRANSACTION_TYPE_NAME
  , TLU1.DESCRIPTION
FROM INV.MTL_TRANSACTION_TYPES TLU1 -- (MTL_MATERIAL_TRANSACTIONS LOOK UPs)
ORDER BY TLU1.TRANSACTION_TYPE_ID;
--
-- EXAMPLE BUILD2PLAN 
--

SELECT 
    WE.WIP_ENTITY_NAME
    , SUM(T.TRANSACTION_QUANTITY) AS ACTUAL_DELIVERY
    , T.TRANSACTION_DATE AS DELIVERY_DATE
    , 'ACTUALDELIVERY' AS FEATURE
    , MS.SEGMENT1
    , T.ORGANIZATION_ID
    , 'ACTUALS DELIVERY' AS SUBFEATURE
FROM APPS.MTL_MATERIAL_TRANSACTIONS T
    INNER JOIN WIP.WIP_ENTITIES WE ON WE.WIP_ENTITY_ID = T.TRANSACTION_SOURCE_ID 
        AND WE.ORGANIZATION_ID = T.ORGANIZATION_ID
        AND T.TRANSACTION_TYPE_ID = 44 -- HERE IS THE USE CASE EXAMPLE
    INNER JOIN INV.MTL_SYSTEM_ITEMS_B MS ON T.INVENTORY_ITEM_ID = MS.INVENTORY_ITEM_ID 
        AND T.ORGANIZATION_ID = MS.ORGANIZATION_ID
WHERE T.ORGANIZATION_ID = 1213 AND T.TRANSACTION_DATE > SYSDATE - 365
GROUP BY MS.SEGMENT1, WE.WIP_ENTITY_NAME, T.TRANSACTION_DATE, T.ORGANIZATION_ID;

--
--
--

/* 
****
****
****    INV.MTL_TXN_SOURCE_TYPES
****
****
****
*/
-- KEYS
-- T.TRANSACTION_SOURCE_TYPE_ID = TLU.TRANSACTION_SOURCE_TYPE_ID
SELECT DISTINCT
    TRANSACTION_SOURCE_TYPE_ID
  , TRANSACTION_SOURCE_TYPE_NAME
  , SUBSTR(DESCRIPTION, 1, 20) AS DESCRIPTION
  , USER_DEFINED_FLAG
FROM INV.MTL_TXN_SOURCE_TYPES TLU 
ORDER BY TRANSACTION_SOURCE_TYPE_ID;

/* 
****
****
****    INV.MTL_TRANSACTION_REASONS
****
****
****
*/
-- KEYS
-- T.REASON_ID = TLU.TRANSACTION_REASONS

SELECT DISTINCT
    REASON_ID
  , REASON_NAME
  , REASON_TYPE
  , WORKFLOW_NAME
FROM INV.MTL_TRANSACTION_REASONS TLU
ORDER BY REASON_ID;

/* 
****
****
****    LU2.LOOKUP_TYPE ='ITEM_TYPE'
****
****
****
*/
SELECT DISTINCT
  LU2.MEANING AS ITEM_TYPE
  , LU2.LOOKUP_TYPE 
  , LU2.LOOKUP_CODE  
FROM
  APPS.FND_LOOKUP_VALUES LU2 
WHERE
  LU2.LOOKUP_TYPE LIKE 'ITEM_TYPE'

ORDER BY LU2.LOOKUP_TYPE , LU2.LOOKUP_CODE;

/* 
****
****
****    LU2.LOOKUP_TYPE ='BOM_ITEM_TYPE'
****
****
****
*/
SELECT DISTINCT
  LU2.MEANING AS BOM_ITEM_TYPE
  , LU2.LOOKUP_TYPE 
  , LU2.LOOKUP_CODE  
FROM
  APPS.FND_LOOKUP_VALUES LU2 
WHERE
  LU2.LOOKUP_TYPE LIKE 'BOM_ITEM_TYPE'

ORDER BY LU2.LOOKUP_TYPE , LU2.LOOKUP_CODE;